### ISSUE TITLE
no ifilter for py3

### ISSUE THREAD

**Issue by axce1** [idlesign/bowerer#1]
```
Traceback (most recent call last):
  File "/home/evgen/git/venv/djtasks/bin/bowerer", line 4, in <module>
    __import__('pkg_resources').run_script('bowerer==0.1.0', 'bowerer')
  File "/home/evgen/git/venv/djtasks/lib/python3.5/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/evgen/git/venv/djtasks/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/home/evgen/git/venv/djtasks/lib/python3.5/site-packages/bowerer-0.1.0-py3.5.egg/EGG-INFO/scripts/bowerer", line 2, in <module>
    from bowerer.console import main
  File "/home/evgen/git/venv/djtasks/lib/python3.5/site-packages/bowerer-0.1.0-py3.5.egg/bowerer/console.py", line 5, in <module>
    from bowerer.api import *
  File "/home/evgen/git/venv/djtasks/lib/python3.5/site-packages/bowerer-0.1.0-py3.5.egg/bowerer/api.py", line 3, in <module>
    from .project import Project
  File "/home/evgen/git/venv/djtasks/lib/python3.5/site-packages/bowerer-0.1.0-py3.5.egg/bowerer/project.py", line 10, in <module>
    from .manager import Manager
  File "/home/evgen/git/venv/djtasks/lib/python3.5/site-packages/bowerer-0.1.0-py3.5.egg/bowerer/manager.py", line 2, in <module>
    from itertools import ifilter
ImportError: cannot import name 'ifilter'

```

**Comment by axce1** [comment]
add patch

```
From fdfb631113ff29466f1ca56306cfeef4b6bfb1fb Mon Sep 17 00:00:00 2001
From: axcel <axce1.github@gmail.com>
Date: Thu, 26 May 2016 11:36:49 +0500
Subject: [PATCH] ifilter for py3

---
 bowerer/manager.py | 8 ++++++--
 1 file changed, 6 insertions(+), 2 deletions(-)

diff --git a/bowerer/manager.py b/bowerer/manager.py
index d0499ac..41761c9 100644
--- a/bowerer/manager.py
+++ b/bowerer/manager.py
@@ -1,7 +1,11 @@
 from os.path import join
-from itertools import ifilter
 from functools import cmp_to_key

+try:
+    from itertools import ifilter as filter
+except ImportError:
+    pass
+
 from semantic_version import compare as v_compare, match as v_match


@@ -213,5 +217,5 @@ class Manager(object):

             return True

-        filtered = ifilter(func_filter, [(idx, endpoint) for idx, endpoint in enumerate(endpoints)])
+        filtered = filter(func_filter, [(idx, endpoint) for idx, endpoint in enumerate(endpoints)])
         return list(filtered)  # todo
-- 
2.8.1
```

**Comment by idlesign** [comment]
Thank you. 
Could you please fork the repo and create a pull request?

**Comment by axce1** [comment]
yep
