### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by axce1** [idlesign/bowerer#2]
```
Trying to read project JSON from /tmp/bowerer ...
Scanning /tmp/bowerer ...
Current candidate: bower.json
Scanning /tmp/bowerer ...
Current candidate: component.json
Scanning /tmp/bowerer ...
Current candidate: .bower.json
Scanning /tmp/bowerer ...
Traceback (most recent call last):
  File "/tmp/bowerer/venvs/bin/bowerer", line 4, in <module>
    __import__('pkg_resources').run_script('bowerer==0.1.0', 'bowerer')
  File "/tmp/bowerer/venvs/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/tmp/bowerer/venvs/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/tmp/bowerer/venvs/lib/python2.7/site-packages/bowerer-0.1.0-py2.7.egg/EGG-INFO/scripts/bowerer", line 2, in <module>
    from bowerer.console import main
  File "/tmp/bowerer/venvs/lib/python2.7/site-packages/bowerer-0.1.0-py2.7.egg/bowerer/console.py", line 153, in <module>
    main()
  File "/tmp/bowerer/venvs/lib/python2.7/site-packages/bowerer-0.1.0-py2.7.egg/bowerer/console.py", line 151, in main
    target_func(**parsed_args)
  File "/tmp/bowerer/venvs/lib/python2.7/site-packages/bowerer-0.1.0-py2.7.egg/bowerer/api.py", line 11, in install
    project.install(endpoints, options, config)
  File "/tmp/bowerer/venvs/lib/python2.7/site-packages/bowerer-0.1.0-py2.7.egg/bowerer/project.py", line 27, in install
    project_json, project_tree, _ = self.analyse()
  File "/tmp/bowerer/venvs/lib/python2.7/site-packages/bowerer-0.1.0-py2.7.egg/bowerer/project.py", line 114, in analyse
    links = self.gather_installed_links()
  File "/tmp/bowerer/venvs/lib/python2.7/site-packages/bowerer-0.1.0-py2.7.egg/bowerer/project.py", line 284, in gather_installed_links
    for directory in listdir(components_path):
OSError: [Errno 2] No such file or directory: '/tmp/bowerer/bower_components'
```

**Comment by idlesign** [comment]
Thank you.
I guess we shouldn't go any further if `components_path` is non existent. Probably need to recheck it against JS source code though.

**Comment by axce1** [comment]
добавил pull request

**Comment by idlesign** [comment]
A few hints:
- You can create a pull request without creating an issue.
- If there's no chance sticking to English, let's prefix pull requests/issues title with `[RU]`, so we could discuss it in russian.
- We shouldn't create any dirs. Watch it:
  https://github.com/bower/bower/blob/master/lib/core/Project.js#L653
  and Nodde.js fs.readdir - https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback
